---
- homebrew_cask: name={{ item }} state=present
  ignore_errors: true
  with_items:
  - google-chrome
  - teamviewer
  - slack
  - forklift
  - cheatsheet
  - virtualbox
  - sublime-text3
  - iterm2
  - postman
  - alfred
  - spectacle
  - android-file-transfer
  - expandrive
  - 1password
  - cheatsheet
  - dash
  - cord
  - shimo
  - phpstorm
  - intellij-idea
  - virtualbox
  - docker